spring.application.name=demo

# Validate the database schema based on your Java classes
spring.jpa.hibernate.ddl-auto=validate
# Show the SQL queries in the console (useful for debugging)
spring.jpa.show-sql=true
